import Head from "next/head";
import { Inter } from "@next/font/google";
import Layout from "@/components/dashboard/layout/Layout";
import { hasCookie, getCookie } from "cookies-next";
import jwt from "jsonwebtoken";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { changeVisible, menuCurrent } from "@/redux/productionSlice";

const inter = Inter({ subsets: ["latin"] });


export default function Home() {
  const dispatch = useDispatch()
  const search_visible = false;
  dispatch(changeVisible({ search_visible }))
  dispatch(menuCurrent({ active_menu: "dashboard" }))
  
  const [user, setuser] = useState({})

  useEffect(() => {

    let validToken = hasCookie("token");
    let getToken = getCookie("token");

    if (!validToken) {
      //window.location.href = "/login";
    } else {
      //console.log("token ", getToken)
      let decodeUser = jwt.decode(getToken)
      //console.log("decode ", decodeUser)
      setuser(decodeUser)
    }
  }, [])


  return (
    <>
      <Head>
        <title>Production House</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className='text-green-600 text-2xl font-bold'>
          Welcome {user.name}!
          {/* {production_id} */}
        </h1>


      </main>
    </>
  );
}


Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};